# Generated by Django 3.1.5 on 2021-03-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210301_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.category'),
        ),
    ]
