# Generated by Django 3.1.5 on 2021-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210302_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
