# Generated by Django 3.1.5 on 2021-03-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210302_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.CharField(max_length=32),
        ),
    ]
