# Generated by Django 3.1.5 on 2021-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210304_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
