# Generated by Django 3.1.5 on 2021-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.CharField(max_length=32),
        ),
    ]
