# Generated by Django 3.1.5 on 2021-03-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210304_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_bids', to='auctions.bid'),
        ),
    ]
