# Generated by Django 3.1.5 on 2021-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_current_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid_user',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
