# Generated by Django 3.1.5 on 2021-03-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20210304_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid_user',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
